// frontend-react/src/pages/board/BoardDetailView.jsx
import React, { useState, useEffect, useCallback } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { fetchBoardDetail, deleteBoard } from '../../api/boardApi';
import styles from './BoardDetailView.module.css';

function BoardDetailView() {
    const { boardType, boardNum } = useParams();
    const navigate = useNavigate();
    const [board, setBoard] = useState(null);
    const [loading, setLoading] = useState(true);

    const loadBoardDetail = useCallback(async () => {
        setLoading(true);
        try {
            const data = await fetchBoardDetail(boardType, boardNum);
            setBoard(data);
        } catch (error) {
            console.error("게시글 상세 정보 로딩 실패:", error);
            alert('게시글을 불러오는 데 실패했습니다.');
        } finally {
            setLoading(false);
        }
    }, [boardType, boardNum]);

    useEffect(() => {
        loadBoardDetail();
    }, [loadBoardDetail]);

    const handleDelete = async () => {
        if (window.confirm("정말로 이 게시글을 삭제하시겠습니까?")) {
            try {
                await deleteBoard(boardType, boardNum);
                alert('게시글이 삭제되었습니다.');
                navigate('/boards');
            } catch (error) {
                console.error("게시글 삭제 실패:", error);
                alert('게시글 삭제에 실패했습니다.');
            }
        }
    };
    
    if (loading) return <p>게시글을 불러오는 중입니다...</p>;
    if (!board) return <p>해당 게시글을 찾을 수 없습니다.</p>;

    return (
        <div className={styles.boardDetail}>
            <h2 className={styles.boardTitle}>{board.boardTitle}</h2>
            <div className={styles.metaInfo}>
                <span>작성자: {board.creator}</span>
            </div>
            <p className={styles.comment}>{board.boardComment}</p>
            <div className={styles.buttonGroup}>
                {/* [수정] 불필요한 className 제거 */}
                <button onClick={() => navigate('/boards')}>
                    목록으로
                </button>
                {board.isOwner && (
                    <div className={styles.ownerButtons}>
                        {/* [수정] 불필요한 className 제거 */}
                        <button onClick={() => navigate(`/boards/edit/${boardType}/${boardNum}`)}>수정</button>
                        <button onClick={handleDelete}>삭제</button>
                    </div>
                )}
            </div>
        </div>
    );
}

export default BoardDetailView;

// frontend-vue/src/views/board/BoardDetailView.vue
<template>
  <!-- template 부분은 변경 없습니다. -->
  <div class="board-detail">
    <div v-if="loading"><p>게시글을 불러오는 중입니다...</p></div>
    <div v-else-if="board" class="board-content">
      <h2>{{ board.boardTitle }}</h2>
      <div class="meta-info"><span>작성자: {{ board.creator }}</span></div>
      <hr>
      <p class="comment" style="white-space: pre-wrap;">{{ board.boardComment }}</p>
      <div class="button-group">
        <button @click="goToList">목록으로</button>
        <div v-if="board.isOwner" class="owner-buttons">
          <button @click="goToEdit">수정</button>
          <button @click="handleDelete">삭제</button>
        </div>
      </div>
    </div>
    <div v-else><p>해당 게시글을 찾을 수 없습니다.</p></div>
  </div>
</template>

<script>
// [수정] apiClient 대신 boardApi 모듈을 가져옵니다.
import { fetchBoardDetail, deleteBoard } from '@/api/boardApi';

export default {
  props: {
    boardType: { type: String, required: true },
    boardNum: { type: [String, Number], required: true }
  },
  data() {
    return {
      board: null,
      loading: true,
    };
  },
  created() {
    this.fetchBoardDetail();
  },
  methods: {
    async fetchBoardDetail() {
      this.loading = true;
      try {
        // [수정] boardApi의 함수를 사용합니다.
        this.board = await fetchBoardDetail(this.boardType, this.boardNum);
      } catch (error) {
        console.error("게시글 상세 정보 로딩 실패:", error);
        alert('게시글을 불러오는 데 실패했습니다.');
        this.board = null;
      } finally {
        this.loading = false;
      }
    },
    goToList() { this.$router.push('/boards'); },
    goToEdit() { this.$router.push(`/boards/edit/${this.boardType}/${this.boardNum}`); },
    async handleDelete() {
      if (confirm("정말로 이 게시글을 삭제하시겠습니까?")) {
        try {
          // [수정] boardApi의 함수를 사용합니다.
          await deleteBoard(this.boardType, this.boardNum);
          alert('게시글이 삭제되었습니다.');
          this.goToList();
        } catch (error) {
          console.error("게시글 삭제 실패:", error);
          alert('게시글 삭제에 실패했습니다.');
        }
      }
    }
  }
}
</script>

<style scoped>
/* style 부분은 변경 없습니다. */
.board-detail{padding:20px;max-width:800px;margin:0 auto}.meta-info{color:#888;margin-bottom:20px}.comment{min-height:200px;line-height:1.6}.button-group{margin-top:20px;text-align:right}.button-group button{margin-left:10px;padding:8px 16px}.owner-buttons{display:inline-block}
</style>
